### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
#ESEMPIO1
#codice normale
n = [1,2,3,4,5]
quadrati = []
for x in n:
    quadrati.append(x**2)
quadrati

#list comprehension
quadrati = [x**2 for x in n]
quadrati

[1, 4, 9, 16, 25]

In [2]:
#ESEMPIO2
#codice normale
nomi = ["ali", "sara", "luca"]
maiuscolo = []
for nome in nomi:
    maiuscolo.append(nome.upper())
maiuscolo

#list comprehension
maiuscolo = [nome.upper() for nome in nomi]
maiuscolo

['ALI', 'SARA', 'LUCA']

In [3]:
#ESEMPIO3
#codice normale
pari = []
for x in range(10):
    if x%2==0:
        pari.append(x)
pari

#list comprehension
pari = [x for x in range(10) if x%2==0]
pari

[0, 2, 4, 6, 8]

### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [ ]:
import numpy as np
#punto1
a = np.array([2,3,5,7])
print(a)
#punto2
print(a.size)
print(len(a))
#punto3
#mi aspetto che dtype mi dia int
print(a.dtype)
#punto4
primi = [n for n in range(11) if n>1 and not [i for i in range(2,n) if n%i==0]]
primi_array = np.array(primi)
primi_array

[2 3 5 7]
4
4
int64


array([2, 3, 5, 7])

### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [2]:
#creo l'array a da 0 a 4 inclusi
import numpy as np
a = np.arange(1,6)
#creo b con lo slicing
b = a[1:4]
#creo c facendo il reverse di a
c = a[::-1]
#divido l'array a per c
divis_array = a/c
#stampo tutti i risultati
print(a)
print(b)
print(c)
print(divis_array)
#LISTA
#creo la lista a da 0 a 4 inclusi
lista_a = list(range(1,6))
#creo b con lo slicing
lista_b = lista_a[1:4]
#creo c facendo il reverse di a
lista_c = lista_a[::-1]
print(lista_a)
print(lista_b)
print(lista_c)
#divisione
risultato = [lista_a[i]/lista_c[i] for i in range(len(lista_a))]
print(risultato)



[1 2 3 4 5]
[2 3 4]
[5 4 3 2 1]
[0.2 0.5 1.  2.  5. ]
[1, 2, 3, 4, 5]
[2, 3, 4]
[5, 4, 3, 2, 1]
[0.2, 0.5, 1.0, 2.0, 5.0]
